
# BASE IMAGE
FROM node:16

# just get the package*.json files and run npm install. 
# This is helpful for using build cache in subseqent build runs if caching is used when building 
COPY package*.json ./
RUN npm install

# copy all app code
COPY . ./

# Add default .mizurc config to the home directory
# TODO(https://github.com/solipsis-project/mizu-client/issues/17): Improve handling of config files
RUN echo '{"storage":"mock","db":"/test.db"}' > /root/.mizurc

# build typescript to javascript
RUN npm run build

#global installation of mizu
RUN npm install -g

# check if mizu is installed and working fine
RUN mizu --version

# default command executed when user runs the container without any command
CMD ["mizu", "--help" ]