name: integration-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  verify-install:
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the current branch of mizu-client repo here.
        uses: actions/checkout@v3


      - name: Set up Docker Buildx
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub (we can even login to other container registries)
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile-linux
          push: true
          tags: user/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      

      - name: Setup node
        if: ${{ matrix.os }} == 'windows-latest'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build
        if: ${{ matrix.os }} == 'windows-latest'
        run: |
          npm install
          npm run build
          npm install -g
          mizu --version


      - name: Regular cleanup of caches used or created in above steps (important)
        run: |
          echo "Yet to implement"
          echo "Reason: Total Cache sizeis limited to 10GB per repository in github at present."